# Default configuration for Self-Evolving CLI Tool
version: "0.1.0"
verbose: false

# LLM Integration Settings
llm:
  use_direct_api: true
  providers: ["gemini"]  # Priority order - Gemini only
  timeout: 30
  temperature: 0.7
  max_tokens: 2000

  # Gemini configuration
  gemini_model: "gemini-2.0-flash"

  # OpenAI configuration (backup)
  openai_model: "gpt-3.5-turbo"

  # Anthropic configuration (backup)
  anthropic_model: "claude-3-sonnet-20240229"

  # Local LLM configuration (backup)
  local_endpoint: "http://0.0.0.0:11434/api/generate"
  local_model: "llama2"

# Code Generation Settings
code_generation:
  validation_enabled: true
  safe_execution: true
  backup_enabled: true
  max_code_length: 10000
  auto_improve: true
  improvement_attempts: 3

# History Management
history:
  max_entries: 1000
  auto_cleanup: true
  backup_path: "backups"
  retention_days: 30

# Plugin System
plugins:
  auto_load: true
  auto_activate: true
  plugin_dirs:
    - "plugins"
  allowed_imports:
    - "os"
    - "sys"
    - "pathlib"
    - "json"
    - "yaml"
    - "click"
    - "datetime"
    - "time"
    - "subprocess"
    - "shutil"
    - "glob"
    - "re"
    - "uuid"
    - "typing"
    - "collections"
    - "itertools"
    - "functools"
    - "argparse"
    - "logging"

# Security Settings
security:
  validation_enabled: true
  strict_mode: true

  # Sandbox configuration
  sandbox_enabled: true
  memory_limit_mb: 50
  cpu_time_limit: 10
  network_access: false

  # Validation timeouts
  max_execution_time: 60
  llm_validation_timeout: 30

  # Restricted operations
  restricted_modules: ["os", "sys", "subprocess", "socket", "urllib", "requests"]
  dangerous_functions: ["eval", "exec", "compile", "__import__", "open"]

  # Pattern detection
  suspicious_patterns:
    - "rm -rf"
    - "format c:"
    - "del /q" 
    - "chmod 777"
    - "sudo"

# Directory Paths
paths:
  generated_dir: "generated"
  plugins_dir: "plugins"
  templates_dir: "templates"
  logs_dir: "logs"
  backups_dir: "backups"

# Logging Settings
logging:
  level: "INFO"
  file_logging: true
  console_logging: true
  max_log_files: 10
  max_log_size_mb: 10

# CLI Settings
cli:
  auto_complete: true
  command_aliases: true
  rich_output: true
  progress_bars: true

# AGI Platform Integration (Future)
agi:
  enabled: false
  endpoint: ""
  api_key: ""
  model_name: ""
  reasoning_enabled: false
  self_reflection: false
  goal_oriented: false